### ISSUE TITLE
Some problems with "ns-ros -h"

### ISSUE THREAD

**Issue by Ian-YJX** [leggedrobotics/radiance_field_ros#3]
I completed necessary configurations and tried to use 

> ns-ros -h

in my terminal. And the output is
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/nerfstudio/bin/ns-ros", line 5, in <module>
    from ros_nerf.scripts.ros_runner import entrypoint
  File "/home/ian/ros1_ws/src/radiance_field_ros/ros_nerf/scripts/ros_runner.py", line 32, in <module>
    from nerfstudio.scripts.exporter import ExportGaussianSplat
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/exporter.py", line 38, in <module>
    from nerfstudio.data.datamanagers.base_datamanager import VanillaDataManager
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 54, in <module>
    from nerfstudio.configs.dataparser_configs import AnnotatedDataParserUnion
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/dataparser_configs.py", line 59, in <module>
    external_dataparsers, _ = discover_dataparsers()
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/plugins/registry_dataparser.py", line 59, in discover_dataparsers
    spec = discovered_entry_points[name].load()
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 183, in load
    module = import_module(match.group('module'))
  File "/root/miniconda3/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'ros_nerf.data'
```
It seems  there should be a "data" file in the "rosnerf" directory. But I checked the repo code and there isn't one. Could anyone help me please? Thanks.

**Comment by maxwildersmith** [comment]
Good catch!

Seems to have been caught in the data .gitignore, the data folder is back, let me know if everything works for you!

**Comment by Ian-YJX** [comment]
Everything works now, thanks a lot!
